#!/bin/bash
/Users/matheus/Downloads/RehabMan-CodecCommander-2018-1003/Release/hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x25
/Users/matheus/Downloads/RehabMan-CodecCommander-2018-1003/Release/hda-verb 0x21 SET_UNSOLICITED_ENABLE 0x83
echo -e "Done"

